import { COLORS, SIZES } from "./theme";

const locations = [
  "Arandis",
  "Aranos",
  "Eenhana",
  "Gobabis",
  "Grootfontein",
  "Helao",
  "Henties Bay",
  "Karasburg",
  "Karibib",
  "Katima Mulilo",
  "Keetmanshoop",
  "Khorixas",
  "Luderitz",
  "Mariental",
  "Nkurenkuru",
  "Okahandja",
  "Okahao",
  "Okakarara",
  "Omaruru",
  "Omuthiya",
  "Ondangwa",
  "Ongwediva",
  "Oniipa",
  "Opuwo",
  "Oranjemund",
  "Oshakati",
  "Oshikango",
  "Oshikuku",
  "Otavi",
  "Otjiwarongo",
  "Outapi",
  "Outjo",
  "Rehoboth",
  "Ruacana",
  "Rundu",
  "Sesriem",
  "Swakopmund",
  "Tsumeb",
  "Usakos",
  "Walvis Bay",
  "Windhoek",
];

export { COLORS, SIZES, locations };
